### ISSUE TITLE
FIXED : Center images

### ISSUE THREAD

**Issue by ouadie-lahdioui** [Raniazy/tuto_slack_botkit_chatbot#1]
Hello,

The first two images in the readme file look so nice, but if you try to center them, they should look better.

**Comment by Raniazy** [comment]
+1 
Je l'ai fait exprès to get comments :smile: it worked, Merci @ouadie-lahdioui

**Comment by ouadie-lahdioui** [comment]
Cool,
it must be fixed not closed !

**Comment by ouadie-lahdioui** [comment]
issue still opened !

It must be fixed (not have a fixed labels) :smiling_imp:

**Comment by ouadie-lahdioui** [comment]
Just close it ...
