### ISSUE TITLE
FIXED : Remove snake case

### ISSUE THREAD

**Issue by ouadie-lahdioui** [Raniazy/tuto_slack_botkit_chatbot#2]
Yo,

Remove snake case : tuto_slack_botkit_chatbot --> Tuto slack botkit chatbot

Juste like : Building steps, Prepare the environnement ....

**Comment by ouadie-lahdioui** [comment]
issue still opened !

It must be fixed (not have a fixed labels) :smiling_imp:

**Comment by ouadie-lahdioui** [comment]
Just close it

**Comment by Raniazy** [comment]
Just leave it. 
All matters is that it's fixed
